In [1]:
import torch

ModuleNotFoundError: No module named 'torch'

In [ ]:
pip install torch

In [ ]:
print("hello")

In [1]:
print("ji")

ji


In [2]:
!pip install torch torchvision torchaudio

  Using cached torch-2.7.1-cp312-cp312-win_amd64.whl.metadata (28 kB)
  Using cached filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
  Using cached fsspec-2025.5.1-py3-none-any.whl.metadata (11 kB)
Using cached torch-2.7.1-cp312-cp312-win_amd64.whl (216.1 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 13.3 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 2.5/2.5 MB 13.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 2.7/2.7 MB 15.5 MB/s eta 0:00:00
Using cached filelock-3.18.0-py3-none-any.whl (16 kB)
Using cached fsspec-2025.5.1-py3-none-any.whl (199 kB)

   ---------------------------------------- 0/6 [pillow]
   ---------------------------------------- 0/6 [pillow]
   ---------------------------------------- 0/6 [pillow]
   ---------------

In [5]:
import torch

print("Pytorch version:", torch.__version__)
print("CUDA avaiable (GPU support):", torch.cuda.is_available())

Pytorch version: 2.7.1+cpu
CUDA avaiable (GPU support): False


In [6]:
import torch
import numpy as np #we will use numpy to show conversions

print("--Creating Tensors--")
#Creating a Tensor from a Python List
# A 1D tensor(vector)
tensor_1d=torch.tensor([1,2,3,4,5])
print("\n1D Tensor (vector):")
print(tensor_1d)
print("Shape:", tensor_1d.shape) #How many elements are there?

--Creating Tensors--

1D Tensor (vector):
tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])


In [9]:
# A 2D tensor (matrix)
tensor_2d= torch.tensor([[10,20,30],[40,50,60]])
print("\n2D Tensor (Matrix):")
print(tensor_2d)
print("Shape:", tensor_2d.shape) #what does (2,3) mean?(rows, columns)


2D Tensor (Matrix):
tensor([[10, 20, 30],
        [40, 50, 60]])
Shape: torch.Size([2, 3])


In [10]:
# 2. Creating a tensor from a Numpy array
numpy_array=np.array([[1,2,3],[4,5,6]])

tensor_from_numpy=torch.from_numpy(numpy_array)
print("\n Tensor from Numpy Array:")
print(tensor_from_numpy)
print("Shape:", tensor_from_numpy.shape)



 Tensor from Numpy Array:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])


In [11]:
# Note: Changes in the Numpy array will affect the tensor and vice versa (they share memory).
numpy_array[0,0]=99
print("Numpy array after change:",numpy_array)
print("Tensor from Numpy after change:", tensor_from_numpy) # See the change reflected!

Numpy array after change: [[99  2  3]
 [ 4  5  6]]
Tensor from Numpy after change: tensor([[99,  2,  3],
        [ 4,  5,  6]])


In [13]:
#Creating tensors of zero, ones, or random values
#All Zeors (2 rows, 3 columns)

zeros_tensor = torch.zeros(2,3)
print("\nZeros Tensor (2x3):")
print(zeros_tensor)


Zeros Tensor (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
#All ones (3 rows, 2 columns)
ones_tensor =torch.ones(3,2)
print("\nOnes Tensor (3x2):")
print(ones_tensor)


Ones Tensor (3x2):
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [15]:
# Random tensor with values between 0 and 1 (uniform distribution)
random_tensor =torch.randn(2,3)
print("\nRandom Normal Tensor (2x3):")
print(random_tensor)


Random Normal Tensor (2x3):
tensor([[-1.5399,  0.9304, -0.5656],
        [ 0.0751, -0.7791,  0.1889]])


In [16]:
# 4. Creating tensors with specific data types (dtype)
#By default, PyTorch infers data types, but you can specify them.

int_tensor=torch.tensor([1,2,3], dtype=torch.int32)
print("\nInteger Tensor (int32):", int_tensor, int_tensor.dtype)


Integer Tensor (int32): tensor([1, 2, 3], dtype=torch.int32) torch.int32


In [17]:
float_tensor=torch.zeros(2,2, dtype=torch.float64) #Float64 is like Python's float
print("Float Tensor (float64):", float_tensor, float_tensor.dtype)

Float Tensor (float64): tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64) torch.float64


In [19]:
# Trying to create a 3D tensor with random values
D_tensor= torch.randn(2,3,4)
print(D_tensor,D_tensor.shape)

tensor([[[ 0.2866, -0.1414,  1.3043,  0.9055],
         [ 2.0557, -0.2497, -0.0369, -1.0538],
         [ 1.1613,  0.8242, -1.0197,  0.4510]],

        [[-0.0290, -1.3981, -0.5839,  0.2034],
         [-1.3309,  0.2953,  0.0097,  0.6668],
         [ 2.5723, -0.4506,  0.3268, -1.3866]]]) torch.Size([2, 3, 4])


In [28]:
# Tensor Operations
# 1. Basic Arithmetic Operations (Element-wise)

tensor_a=torch.tensor([[1,2],[3,4]])
tensor_b=torch.tensor([[5,6],[7,8]])

print("\nTensor A:\n", tensor_a)
print("\nTensor B:\n", tensor_b)

print("\nElement-wise Addition (A+B):\n", tensor_a+tensor_b)
print("\nElement-wise Multiplication (A*B):\n", tensor_a*tensor_b)
print("\nElement-wise Divison (A/B):\n", tensor_a/tensor_b) #Note: Will convert to float if not already.

# Scalar operations
print("\nScalar Multiplication (A*2):\n", tensor_a*2)
print("Scalar Addition (A+10):\n", tensor_a+10)


# 2. Matrix Multiplication (Dot Product)
# This is fundamental for neural networks!
# Remember the rule: (m x n) @ (n x p) = (m x p)

matrix1= torch.tensor([[1,2],[3,4]]) #Shape (2,2)
matrix2= torch.tensor([[5,6],[7,8]]) #Shape (2,2)

print("\nMatrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)

# Using the @ operator (preferred for matrix multiplication)

matrix_mult_res= matrix1 @ matrix2
print("Matrix Multiplication (matrix1 @ matrix2):\n", matrix_mult_res)

#using torch.matmul()
matrix_mult_res_func=torch.matmul(matrix1, matrix2)
print("Matrix Multiplication (torch.matmul(matrix1, matrix2):\n",matrix_mult_res_func)




Tensor A:
 tensor([[1, 2],
        [3, 4]])

Tensor B:
 tensor([[5, 6],
        [7, 8]])

Element-wise Addition (A+B):
 tensor([[ 6,  8],
        [10, 12]])

Element-wise Multiplication (A*B):
 tensor([[ 5, 12],
        [21, 32]])

Element-wise Divison (A/B):
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

Scalar Multiplication (A*2):
 tensor([[2, 4],
        [6, 8]])
Scalar Addition (A+10):
 tensor([[11, 12],
        [13, 14]])

Matrix 1:
 tensor([[1, 2],
        [3, 4]])

Matrix 2:
 tensor([[5, 6],
        [7, 8]])
Matrix Multiplication (matrix1 @ matrix2):
 tensor([[19, 22],
        [43, 50]])
Matrix Multiplication (torch.matmul(matrix1, matrix2):
 tensor([[19, 22],
        [43, 50]])


In [37]:
# 3. Reshaping Tensors
original_tensor= torch.arange(9) #creates a 1D tensor from 0 to 8
print("\nOriginal 1D tensor (0-8):\n", original_tensor)

#Reshape to a 3x3 matrix
reshaped_3x3 =original_tensor.reshape(3,3)
print("Reshaped to 3x3:\n", reshaped_3x3)
original_tensor[0]=99


Original 1D tensor (0-8):
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
Reshaped to 3x3:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [39]:
#Reshape using .view() -often shares memory with original
reshape_view= original_tensor.view(3,3)
print("Reshaped using .view(3,3):\n", reshape_view)
# Note: If you change original_tensor, reshaped_view might change too if they share memory.
# For a copy, use .clone()

# Flatten a tensor (eg, for input to a linear layer)
flattened_tensor = reshaped_3x3.view(-1) # -1 infers the size of that dimension
print("Flattened 3x3 tensor:\n", flattened_tensor)

Reshaped using .view(3,3):
 tensor([[99,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]])
Flattened 3x3 tensor:
 tensor([99,  1,  2,  3,  4,  5,  6,  7,  8])


In [40]:
#4. Indexing and Slicing Tensors (Just like Numpy!)
data_tensor = torch.tensor([[10, 20, 30, 40],
                            [50, 60, 70, 80],
                            [90, 100, 110, 120]])
print("\nOriginal Data Tensor:\n", data_tensor)
# Access a single element (row 0, column 1)
element = data_tensor[0,1]
print("Element at (0,1):", element)

# Slice the first row (all columns)
first_row = data_tensor[0, :]
print("First Row:", first_row)

# Slice the second column (all rows)
second_column = data_tensor[:, 1]
print("Second Column:", second_column)

# Slice a sub-matrix (rows 0 to 1, columns 2 to 3)
sub_matrix = data_tensor[0:2, 2:4]
print("Sub-matrix (rows 0-1, cols 2-3):\n", sub_matrix)

# Using integer indexing (select specific rows/columns)
specific_elements = data_tensor[[0, 2], [0, 3]] # Element at (0,0) and (2,3)
print("Specific elements (0,0) and (2,3):", specific_elements)




Original Data Tensor:
 tensor([[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])
Element at (0,1): tensor(20)
First Row: tensor([10, 20, 30, 40])
Second Column: tensor([ 20,  60, 100])
Sub-matrix (rows 0-1, cols 2-3):
 tensor([[30, 40],
        [70, 80]])
Specific elements (0,0) and (2,3): tensor([ 10, 120])


In [42]:
#mini exercise
arr1=torch.randn(4,3)
arr2= torch.randn(3,2)
mul=arr1@arr2
print(mul, mul.shape)


tensor([[-0.1094,  0.5996],
        [-0.3362,  0.0879],
        [-1.5134,  0.6372],
        [-0.7322,  0.8461]]) torch.Size([4, 2])


In [ ]:
#CPU vs. GPU (Device Management)
#Neural networks involve a massive amount of numerical computation, especially matrix multiplications. While CPUs can handle these, GPUs (Graphics Processing Units) are specifically designed for parallel processing of large arrays of data and can perform these computations many times faster than CPUs.

#CPU (Central Processing Unit): Your computer's main processor. Good for general-purpose tasks and sequential operations.
#GPU (Graphics Processing Unit): A specialized processor optimized for parallel computation. Essential for accelerating deep learning training, especially on large datasets. NVIDIA GPUs are typically used with CUDA.
#PyTorch allows you to easily move tensors and models between your CPU and GPU.

In [44]:
import torch

print("--Device Management (CPU vs GPU)--")

#1. Check if GPU is avaiable (CUDA)
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("\nGPU (CUDA) is avaiable. Using GPU!")
else:
    device=torch.device("cpu")
    print("\nGPU (CUDA) is NOT avaiable. Using CPU.")


--Device Management (CPU vs GPU)--

GPU (CUDA) is NOT avaiable. Using CPU.


In [45]:
#2. Create a tensor on CPU (default)
cpu_tensor=torch.tensor([1,2,3])
print("\nTensor on CPU:", cpu_tensor)
print("Device of cpu_tensor:",cpu_tensor.device)


Tensor on CPU: tensor([1, 2, 3])
Device of cpu_tensor: cpu


In [46]:
#3. Move the tensor to the determined device (GPU if avaiable, else stay on CPU)
# .to(device) moves the tensor. It returns a NEW tensor on the target device.
# It does NOT modify the tensor in-place.
tensor_on_device = cpu_tensor.to(device)
print("\n Tensor moved to device:",tensor_on_device)
print("Device of tensor_on_device:", tensor_on_device.device)


 Tensor moved to device: tensor([1, 2, 3])
Device of tensor_on_device: cpu


In [47]:
#4. Create a tensor directly on the GPU (if avaiable)
if torch.cuda.is_available():
    gpu_tensor_direct= torch.tensor([4,5,6], device=device)
    print("\nTensor created directly on GPU:", gpu_tensor_direct)
    print("Device of gpu_tensor_direct:", gpu_tensor_direct.device)
else:
    print("\nCannot create tensor directly on GPU, as GPU is not available.")

# Important Note: You cannot perform operations directly between tensors on different devices.
# They must be on the same device.
# Example: If cpu_tensor is on CPU and gpu_tensor_direct is on GPU, you CANNOT do cpu_tensor + gpu_tensor_direct.
# You would need to move one to the other's device first:
# result = cpu_tensor.to(device) + tensor_on_device  # Both are now on the same device
    


Cannot create tensor directly on GPU, as GPU is not available.


In [53]:
#mini Exercise
#1. Create a 2x2 tensor 'my_data', filled with ones on the CPU.
#2. If a GPU is available, move my_data to the GPU. Otherwise, ensure it remains on the CPU.
#3. Print my_data and confirm its device.

import torch

my_data=torch.ones(2,2)
print("Initial my_data (on CPU):")
print(my_data)
print("Initial device:", my_data.device)

#Determine the device to use (GPU if available, else CPU)
if torch.cuda.is_available():
    device=torch.device("cuda")
    print("\nGPU (CUDA) is available. Moving tensor to GPU.")
    my_data=my_data.to(device)
else:
    device=torch.device("cpu")
    print("\n No GPU avaiable so tensor remains on cpu")






Initial my_data (on CPU):
tensor([[1., 1.],
        [1., 1.]])
Initial device: cpu

 No GPU avaiable so tensor remains on cpu
