In [2]:
import numpy as np

In [2]:
pip3 install numpy


SyntaxError: invalid syntax (1773489910.py, line 1)

In [3]:
pip3 install numpy

SyntaxError: invalid syntax (3889239008.py, line 1)

In [4]:
python --version

NameError: name 'python' is not defined

In [5]:
python --version

NameError: name 'python' is not defined

In [6]:
python3 --version

NameError: name 'python3' is not defined

In [7]:
import sys
print(sys.version)

3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]


In [8]:
!python --version

Python 3.12.4


In [9]:
pip install numpy


   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   --------- ------------------------------ 3.1/12.7 MB 14.2 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.7 MB 16.8 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.7 MB 18.0 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 16.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
import numpy as np
print("NumPy imported successfully!")

NumPy imported successfully!


In [4]:
#create a 1D array (vector)
a=np.array([1,2,3,4,5])
print("1D Array 'a' :",a)
print("Shape of 'a':", a.shape)

1D Array 'a' : [1 2 3 4 5]
Shape of 'a': (5,)


In [6]:
# create a 2D array (vector)
b=np.array([[10,11,12],[13,14,15]])
print("\n2D Array 'b':\n",b)
print("shape of 'b':", b.shape)


2D Array 'b':
 [[10 11 12]
 [13 14 15]]
shape of 'b': (2, 3)


In [7]:
#create an array of all zeros (3 rows, 4 columns)
zeros_matrix =np.zeros((3,4))
print("\nZeros Matrix (3x4):\n", zeros_matrix)


Zeros Matrix (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
#create an array of all ones (2 rows, 2 columns)
ones_matrix=np.ones((2,2))
print("\nOnes MAtrix (2x2):\n", ones_matrix)


Ones MAtrix (2x2):
 [[1. 1.]
 [1. 1.]]


In [14]:
#create an identity matrix (3x3) -useful in linear algerbra
identity_matrix =np.eye(8)
print("\nIdentity Matrix (3x3):\n", identity_matrix)


Identity Matrix (3x3):
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [15]:
#indexing and slicing array
my_array =np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print("Orginal Array:\n", my_array)


Orginal Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [16]:
#Acess a single element (row 0, column 1)
element = my_array[0,1]
print("\nElement at (0,1):", element)


Element at (0,1): 20


In [17]:
#slice the first row (all columns)
first_row=my_array[0,:]
print("\nFirst row:\n", first_row)


First row:
 [10 20 30 40]


In [19]:
#slice the second column (all rows)
sec_column=my_array[:,1]
print("second column:", sec_column)

second column: [ 20  60 100]


In [20]:
#slice a sub-matrix( rows 0 to 1, columns 2 to 3)
sub_matrix =my_array[0:2,2:4]
print("Sub matrix (rows 0-1,cols 2-3:\n", sub_matrix)

Sub matrix (rows 0-1,cols 2-3:
 [[30 40]
 [70 80]]


In [21]:
print("Orginal Array:\n", my_array)


Orginal Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [25]:
sub=my_array[0,1:3]
print(sub)

[20 30]


In [26]:
#basic Operations(Element-wise):
arr_a=np.array([[1,2],[3,4]])
arr_b=np.array([[5,6],[7,8]])

print("\nArray A:\n", arr_a)
print("\nArray B:\n", arr_b)



Array A:
 [[1 2]
 [3 4]]

Array B:
 [[5 6]
 [7 8]]


In [27]:
#Element-wise addition
print("\nElement-wise A+B:\n", arr_a+arr_b)



Element-wise A+B:
 [[ 6  8]
 [10 12]]


In [28]:
#Element-wise multiplication
print("\nElement-wise A+B:\n", arr_a*arr_b)



Element-wise A+B:
 [[ 5 12]
 [21 32]]


In [29]:
#scalar multiplication
print("A*5\n", arr_a*5)


A*5
 [[ 5 10]
 [15 20]]


In [31]:
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])

print("matrix1:\n", matrix1)
print("matrix2:\n",matrix2)

matrix1:
 [[1 2]
 [3 4]]
matrix2:
 [[5 6]
 [7 8]]


In [34]:
#matrix multiplication using np.dot()
#dot_prod_res=np.dot(matrix1,matrix2)
#matrix multipliaction using '@' Operator
dot_prod_res=matrix1@matrix2
print("\nDot Product (m1,m2) using np.dot():\n", dot_prod_res)


Dot Product (m1,m2) using np.dot():
 [[19 22]
 [43 50]]


In [3]:
#Reshaping Arrays
Original_flat=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Original flat array:", Original_flat)

Original flat array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
#Reshape to 3 rows, 3 columns
reshape_3x3 = Original_flat.reshape((1,12))
print("\nReshaped to 3x3:\n", reshape_3x3)


Reshaped to 3x3:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
